In [1]:
import numpy as np
np.random.seed = 42

### basics

In [2]:
# 1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D array float
b = np.array([[9.0, 9.9,7.7], 
              [6.6,5.5,4.4]])
print(b)

[[9.  9.9 7.7]
 [6.6 5.5 4.4]]


In [4]:
# get dimention
a.ndim

1

In [5]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# get Type
a.dtype

dtype('int64')

In [7]:
# get itemsize - int64 -- 8 bytes
print(a.itemsize)

# get size - 3
print(a.size) 

# get nbytes = size * itemsize
print(a.nbytes)

8
3
24


In [8]:
# copy the array
c = a.copy()
print(c)

[1 2 3]


### Accessing/ changing specific elements

In [9]:
a = np.array([[1,2,3,4,5,6,7],
            [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# get a specific element
print(a[1,1])

# get a specific row
print(a[0,:])

9
[1 2 3 4 5 6 7]


In [11]:
# [startindex:endindex:stepsize]
a[0, 1: -1: 2]

array([2, 4, 6])

### Initializing different types of arrays

In [12]:
# all 0s matrix
print(np.zeros((2,3,3)))

# all 1s matrix
print(np.ones((4,2,2), dtype = "int32"))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [13]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [14]:
# any other number (full_ like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [15]:
# random decimal numbers
np.random.rand(4,2) # [0-1]

array([[0.41102609, 0.67343585],
       [0.1510454 , 0.2002589 ],
       [0.36728079, 0.48244059],
       [0.06528664, 0.62022244]])

In [16]:
# random integer values
print(np.random.randint(7, size=(3,3))) # [0 to 7]
print(np.random.randint(-4,8, size=(3,3))) # [-4 to 8]

[[4 3 4]
 [5 5 5]
 [3 2 3]]
[[ 1 -1  4]
 [ 4  5  5]
 [ 5 -1  6]]


In [17]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Mathematics

In [18]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [19]:
print(a + 2)
print(a * 2)
print(a**2)

[3 4 5 6]
[2 4 6 8]
[ 1  4  9 16]


In [20]:
b = np.array([1,0,1,0])
print(a + b)

[2 2 4 4]


### Linear Algebra - https://numpy.org/doc/stable/reference/routines.linalg.html

In [21]:
a = np.ones((2,3))
b = np.full((3,2), 2)
print(a)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [22]:
# find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

### Statistics

In [23]:
stats = np.array([[1,2,3], [4,5,6]])

In [24]:
print(np.min(stats, axis=0)) # axis=0 -- column 
print(np.max(stats)) # max of all

[1 2 3]
6


In [25]:
print(np.sum(stats, axis=0)) # axis=0 - column

[5 7 9]


### Reorganizing arrays

In [26]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
# vertically & horizontal stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))

h1 = np.zeros((2,4))
h2 = np.ones((2,4))
print(np.hstack([h1,h2]))

[[1 2 3 4]
 [5 6 7 8]]
[[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


### Miscellaneous

In [28]:
data = np.random.randint(10,50,size=(3,18))
print(data)
print(data.shape)

[[19 30 43 37 39 35 28 22 22 14 14 44 10 18 40 47 26 17]
 [37 41 12 41 47 38 29 39 32 43 14 17 42 13 13 42 45 22]
 [18 36 36 24 11 31 29 21 33 16 21 43 11 25 37 15 10 37]]
(3, 18)


In [29]:
any_20 = np.any(data > 20, axis=0) # any of the column value is greater than 20 
any_20.shape
print(any_20)

all_20 = np.all(data > 20, axis=0) # all of the column value is greater than 20 
all_20.shape
print(all_20)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[False  True False  True False  True  True  True  True False False False
 False False False False False False]


In [30]:
print(data > 20)
print((data>20) & (data<30))

[[False  True  True  True  True  True  True  True  True False False  True
  False False  True  True  True False]
 [ True  True False  True  True  True  True  True  True  True False False
   True False False  True  True  True]
 [False  True  True  True False  True  True  True  True False  True  True
  False  True  True False False  True]]
[[False False False False False False  True  True  True False False False
  False False False False  True False]
 [False False False False False False  True False False False False False
  False False False False False  True]
 [False False False  True False False  True  True False False  True False
  False  True False False False False]]
